
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jul 06 19:35:51 BRT 2021
//----------------------------------------------------

package code;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Else = 6;
  public static final int Colon = 15;
  public static final int For = 27;
  public static final int Parentheses_o = 13;
  public static final int Char = 4;
  public static final int CharName = 26;
  public static final int Float = 3;
  public static final int Break = 25;
  public static final int Default = 22;
  public static final int Int = 2;
  public static final int Parentheses_c = 14;
  public static final int Op_mathematic = 8;
  public static final int Semicolon = 20;
  public static final int Identifier = 21;
  public static final int EOF = 0;
  public static final int Op_relational = 11;
  public static final int Case = 10;
  public static final int Braces_o = 16;
  public static final int Brackets_o = 18;
  public static final int If = 5;
  public static final int error = 1;
  public static final int Switch = 24;
  public static final int Equal = 7;
  public static final int While = 9;
  public static final int Braces_c = 17;
  public static final int Brackets_c = 19;
  public static final int Op_increase = 12;
  public static final int Number = 23;
}

