
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jun 27 20:59:02 BRT 2021
//----------------------------------------------------

package code;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Type_data = 4;
  public static final int Else = 8;
  public static final int For = 11;
  public static final int ERROR = 32;
  public static final int Int = 5;
  public static final int Multiplication = 15;
  public static final int Sum = 13;
  public static final int Op_logical = 17;
  public static final int Semicolon = 29;
  public static final int Main = 28;
  public static final int Identifier = 30;
  public static final int Op_boolean = 21;
  public static final int EOF = 0;
  public static final int Array = 6;
  public static final int Op_relational = 18;
  public static final int Quotes = 3;
  public static final int Division = 16;
  public static final int Braces_o = 24;
  public static final int Brackets_o = 26;
  public static final int If = 7;
  public static final int Parenthesis_o = 22;
  public static final int Line = 2;
  public static final int error = 1;
  public static final int Do = 9;
  public static final int Equal = 12;
  public static final int While = 10;
  public static final int Braces_c = 25;
  public static final int Brackets_c = 27;
  public static final int Op_increase = 20;
  public static final int Parenthesis_c = 23;
  public static final int Number = 31;
  public static final int Op_attribution = 19;
  public static final int Subtraction = 14;
}

