
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jun 28 18:11:41 BRT 2021
//----------------------------------------------------

package code;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Else = 7;
  public static final int Colon = 17;
  public static final int Parentheses_o = 15;
  public static final int Char = 5;
  public static final int Float = 4;
  public static final int ERROR = 29;
  public static final int Break = 27;
  public static final int Default = 24;
  public static final int Int = 3;
  public static final int Parentheses_c = 16;
  public static final int Op_mathematic = 9;
  public static final int Op_logical = 12;
  public static final int Semicolon = 22;
  public static final int Identifier = 23;
  public static final int EOF = 0;
  public static final int Op_relational = 13;
  public static final int Braces_o = 18;
  public static final int Case = 11;
  public static final int Brackets_o = 20;
  public static final int If = 6;
  public static final int Line = 2;
  public static final int error = 1;
  public static final int Switch = 26;
  public static final int Equal = 8;
  public static final int Literal = 28;
  public static final int While = 10;
  public static final int Braces_c = 19;
  public static final int Brackets_c = 21;
  public static final int Op_increase = 14;
  public static final int Number = 25;
}

